# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
