# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_auto_20170919_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.Author'),
        ),
    ]
