# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_auto_20170919_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='origin_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.Stream'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
