# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_auto_20170919_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
