# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
